apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-a
  template:
    metadata:
      labels:
        app: container-a
    spec:
      containers:
      - name: ubuntu-ssh
        image: enzo2346/ubuntu-ssh:latest
        ports:
        - containerPort: 22
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: container-a
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30221
  - name: api
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30799
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-b
  template:
    metadata:
      labels:
        app: container-b
    spec:
      containers:
      - name: ubuntu-ssh
        image: enzo2346/ubuntu-ssh:latest
        ports:
        - containerPort: 22
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: container-b
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30222
  - name: api
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30800
